FROM python:3.12-slim

#crear una carpeta de trabajo
WORKDIR /app

#Copiar requerimientos
COPY requirements.txt .

#instalados
RUN pip install --no-cache-dir -r requirements.txt

#copiar el codigo del proyecto
COPY ./app /app

#Exponer el puerto
EXPOSE 8080

#Comandos para ejecutar FASTAPI
CMD [ "uvicorn","app.main:app","--host","0.0.0.0","--port","8080", "--reload" ]

